import type { Nuxt } from '@nuxt/schema'
import type { Unimport } from 'unimport'
import type { NustackContext } from './context'
import { existsSync } from 'node:fs'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join, relative } from 'node:path'
import { resolveAlias } from '@nuxt/kit'
import { resolveModuleFlags } from './context/module-flags'

const TAILWIND_IMPORT_PATTERN = /@import\s+["']tailwindcss["']/

interface NitroWithUnimport {
  unimport?: Unimport
}

type NitroInitHook = (name: 'nitro:init', handler: (nitro: NitroWithUnimport) => void) => void

/** Registers hooks that regenerate the project-aware ESLint context. */
export function setupNustackContext(nuxt: Nuxt): void {
  let unimport: Unimport | undefined
  let nitroUnimport: Unimport | undefined
  let components: string[] = []

  nuxt.hook('imports:context', (importsContext) => {
    unimport = importsContext
  })
  ;(nuxt.hook as unknown as NitroInitHook)('nitro:init', (nitro) => {
    nitroUnimport = nitro.unimport
  })
  nuxt.hook('components:extend', (list) => {
    components = [...new Set(list.map(component => component.pascalName))].sort()
  })

  async function collectAutoImports(): Promise<string[]> {
    const names = [
      ...await unimport?.getImports() ?? [],
      ...await nitroUnimport?.getImports() ?? [],
    ]
      .filter(importEntry => !importEntry.type)
      .map(importEntry => importEntry.as || importEntry.name)
      .filter((name): name is string => Boolean(name))
    return [...new Set(names)].sort()
  }

  function detectModules(): NustackContext['modules'] {
    const installed = new Set<string>()
    for (const installedModule of nuxt.options._installedModules ?? []) {
      const name = installedModule.meta?.name
      if (name)
        installed.add(name)
    }
    for (const moduleEntry of nuxt.options.modules ?? []) {
      if (typeof moduleEntry === 'string')
        installed.add(moduleEntry)
    }

    return resolveModuleFlags(installed)
  }

  async function detectTailwind(): Promise<NustackContext['tailwind']> {
    for (const entry of nuxt.options.css ?? []) {
      if (typeof entry !== 'string' || !entry.endsWith('.css'))
        continue
      const absolutePath = resolveAlias(entry, nuxt.options.alias)
      if (!existsSync(absolutePath))
        continue
      try {
        const source = await readFile(absolutePath, 'utf-8')
        if (TAILWIND_IMPORT_PATTERN.test(source)) {
          return {
            detected: true,
            // better-tailwindcss resolves `entryPoint` relative to the lint cwd
            // (the project root), so store it relative to rootDir.
            entryPoint: relative(nuxt.options.rootDir, absolutePath),
          }
        }
      } catch {
        // unreadable css entry, ignore and keep scanning
      }
    }
    return { detected: false, entryPoint: null }
  }

  async function buildContext(): Promise<NustackContext> {
    return {
      modules: detectModules(),
      nuxtUi: { prefix: (nuxt.options as any).ui?.prefix ?? 'U' },
      tailwind: await detectTailwind(),
      autoImports: await collectAutoImports(),
      components,
    }
  }

  async function writeContextFile(): Promise<void> {
    const context = await buildContext()
    const file = join(nuxt.options.buildDir, 'nustack-eslint.mjs')
    await mkdir(dirname(file), { recursive: true })
    await writeFile(file, generateCode(context), 'utf-8')
  }

  // `builder:generateApp` runs on `nuxt prepare`, dev and build, after the
  // imports/components registries are populated.
  nuxt.hook('builder:generateApp', writeContextFile)
}

/** Serializes the resolved context into the generated ESM module. */
export function generateCode(context: NustackContext): string {
  return [
    '// Generated by @nustackjs/lint, do not edit.',
    '// Regenerated on every `nuxt prepare`.',
    `import { applyNustackConfig } from '@nustackjs/lint/config'`,
    `import withNuxt from './eslint.config.mjs'`,
    '',
    `export const nustackContext = ${JSON.stringify(context, null, 2)}`,
    '',
    '/** Creates the project ESLint config from options and additional flat configs. */',
    'export function nustack(options = {}, ...configs) {',
    `  return applyNustackConfig(withNuxt(), { target: 'nuxt-app', ...options, context: nustackContext }, ...configs)`,
    '}',
    '',
    'export const nustackLint = nustack',
    '',
    '// Default export = the ready-to-use config, so `export { default } from` works.',
    'export default nustack()',
    '',
  ].join('\n')
}
